version: '3.9'
services:
  backend:
    build:
      context: ./mondeo
      dockerfile: Dockerfile
    #command: 'python main.py'
    expose:
      - "5002"
    ports:
      - "5002:5002"
    volumes:
      - .:/app