version: '3.9'
services:
  backend:
    build:
      context: ./mondeo
      dockerfile: Dockerfile
    expose:
      - "5002"
    environment:
      FLASK_DEBUG: "on"
      FLASK_APP: ./main.py
    ports:
      - "5002:5002"
    volumes:
      - ./mondeo:/mondeo